import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import tw from "tailwind-styled-components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Uber Web 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Map>Map</Map>
        <ActionItems>Start</ActionItems>
      </Wrapper>
    </>
  );
}

const Wrapper = tw.div`
  flex
  flex-col
  bg-blue-500
  h-screen
`;

const Map = tw.div`
  flex-1
  bg-red-500
`;

const ActionItems = tw.div`
  flex-1
  bg-green-500
`;
