import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import tw from "tailwind-styled-components";
import Map from "./components/Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Uber Web 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Map />
        <ActionItems>Start</ActionItems>
      </Wrapper>
    </>
  );
}

const Wrapper = tw.div`
  flex
  flex-col
  bg-blue-500
  h-screen
`;

const ActionItems = tw.div`
  flex-1
  bg-green-500
`;
